Update examples.md with logout in Python
zerotier/docs pull request #217
Opened 2024-10-30 18:58 UTC by aaronjohnson

Document the several steps in code which are required to both deauthorize and remove the secret required during a _logout_.

2024-10-30 19:05 UTC, glimberg commented
I have a lot of questions on this

2024-10-30 19:09 UTC, glimberg commented
First.. What is being accomplished by this PR?  Why is it here?   This doesn't seem to solve a general problem that needs to be documented on the docs site.  Seems more like an attempt to help solve something for a specific customer with a weird workflow, and not something we should document in general.  And even so, I don't think it accomplishes what this change says it's doing.  So i'm really confused here

2024-10-30 19:09 UTC, glimberg requested changes

2024-10-30 19:09 UTC, glimberg commented on docs/api/central/examples.md
> +            token_path = '/var/lib/zerotier-one/authtoken.secret'
Why are you removing authtoken.secret?

2024-10-30 22:54 UTC, rcoder commented
So I believe the basic question being addressed here is, "what can I do if I want the device I'm sitting at to be _immediately_ deauthorized from one or more ZeroTier networks?"

In the normal case, we can't do that due to the design of the ZT1 protocol. The fact that network membership is eventually consistent is a win for resilience and scale, but does cause confusion at best, and real user issues at worst, where the timeout on the existing membership/network config is too long.

It's an edge case, and deleting the local node identity is something we shouldn't point people to by default as it's an inherently unsafe action. (Once lost, that ID ain't coming back.)

OTOH, people go through all kinds of contortions and random troubleshooting steps trying to figure out why de-auths aren't immediate, and have even gone so far as to claim that ZeroTier is inherently "insecure" because we can't do atomic, immediate eviction of network members. Noting a workaround that allows people with the need or desire to see membership change _right now_ seems worthwhile to me.

I do think we can specifically note that the identity deletion is an extra step only needed in specific cases. The current text could be read as saying, "you _should_ do this to be safe," whereas the message we want to covey is more like, "if normal de-auth isn't fast or complete enough for you, you _can_ take this somewhat more severe action...but here be dragons." (etc.)

2024-10-30 23:03 UTC, glimberg commented
@rcoder Yes, deleting an identity & restarting zerotier is probably the only way to go for completely removing a node from authorization immediately.  The code in the example in this PR deletes `authtoken.secret` which is the API key used by `zerotier-cli` and the desktop UI to communicate with the background service.  It doesn't have anything at all to do with SSO sesions or billing or the identity or anything else.  So I'm not even sure what solution this documentation is trying to solve in the first place because it doesn't make any sense to begin with.

2024-10-30 23:43 UTC, glimberg requested changes

2024-10-30 23:43 UTC, glimberg commented on docs/api/central/examples.md
> +
This is still incorrect on a few of levels.  

1) It still references `authtoken.secret`
2) Removing `authtoken.secret` doesn't reset SSO.  Just the API key that `zerotier-cli` and the Desktop UI use to communicate with the service
3) The node remains authorized until the lifetime of the access token used to authorize it expires.  
4) Assuming you mean `identity.secret` here, it will not prevent unbound incremental billing as it'll be a new node ID and charged anyway.

2024-10-31 15:30 UTC, laduke commented
Thanks for making this. I think updating the docs instead of sending bespoke comments to every support case is something we need to do a lot more. 

But this particular case is too highly specific to one specific user doing an unsupported thing *. I don't want people coming across this and trying to do it. People blindly copy and paste things and deleting the identity is unrecoverable. 

It's not a matter of fixing a couple things in the PR but the idea itself. Sorry to say. 

At least we learned a lot about the internals of the client in the process. 

hope that helps


\* user is trying to share 1 computer / node with multiple people. The node is using SSO to auth with a zerotier network. They want each person using the computer to have to re-auth with zerotier. This customer is on a canceled essential trial. 


If de-authorizing a non-sso member doesn't work correctly, we should fix that.  
If there is something confusing about sso (de)authorization, we should note that somewhere appropriate and improve the central design for it.

2025-02-13 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zerotier/docs?pullRequest=217) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zerotier/docs?pullRequest=217) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zerotier/docs?pullRequest=217) it.</sub>

2025-07-03 19:34 UTC, closed without merging